"""alterar coluna name para nome

Revision ID: 2885ad389eaf
Revises: 228e6d8e906e
Create Date: 2026-04-26 20:37:25.255138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2885ad389eaf'
down_revision = '228e6d8e906e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('nome')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
